#!/usr/bin/env bash
# Build and deploy to Cloudflare Pages.

set -euo pipefail

node bs/build

npx wrangler pages deploy ./dist \
  --project-name inbox-rho-ie \
  --branch main \
  --commit-dirty=true
